language: go
go: 1.8.3
install: rake setup
script: rake fmt
after_success:
- bash <(curl -s https://codecov.io/bash)
- test -n "$TRAVIS_TAG" && curl -sL http://git.io/goreleaser | bash
notifications:
  email: false
env:
  matrix:
    secure: KU1ndWVx++OZCf9d77hBoYvZ+O3pptjTfcBIopIHwguJeKmD9AntHyBOSn+kkASVmkfPD3V5uhZU84QzV4di5oWfpR07lP7lCjCeGy0RDydHrlAaXBwmgJv/LHYHjrXrJafyExrqlkblxJxwKimChA+lo4WsAvVhcH3WNyCM/fiSaVOXloauHVbUpNtZ40XqbcLXFbtCZI3CqlZLz5whw7r1wQMqWO5uKojbbcXN6MwRS2NG8/xmk78BBZ06omkqjQ2De4O3sqwRQnlMKR0pCzTEJk1OcRyYfBVyBvYdmX5eQuf7rwcxcnrDHxCXvA1Leq3jW7iYIkTWYe5sYuKJctZUrBwHQgXtsyy7UOt7Zm91yrU4GBcEkvOGX8yGVOIovrbxtpB98xDcGnY78xw9B1ixmdTgQA+xtussBz0YTqOIR9NJkfLmtJq728WEDdYQU0ga0Yo3BW89LcFtzxN+oVHDKXHs7C4eZY8L9COIB6jAV6gyU1t5mtYi/AHq2KHwXaW40X6Ci6WhW+TlhXXJB1yN8PjyBv327w1QGlAVBT0AIyqtG25auXnFGU3cutcvYiOt4XkIF2rPOCpZjAMubPQHTFLumfYcVYeR/497CDJb2eu0k770HollXHWk0Zol7ratwVXp4f/Rwxvf1hSWa9DBzjCTwraveP5PlZZrV7I= #GITHUB_TOKEN
